//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSL_SMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRoleMapping
    {
        public int Id { get; set; }
        public Nullable<int> TblUserId { get; set; }
        public Nullable<int> UserRoleId { get; set; }
    
        public virtual TbleUser TbleUser { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
